=== ManInMyVan/Minecraft-Anticheat-List/src/jsMain/resources/schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Anticheat",
  "description": "Schema for anticheat entries.",
  "type": "object",
  "required": ["platforms", "status", "versions", "price"],
  "properties": {
    "platforms": {
      "type": ["array", "null"],
      "uniqueItems": true,
      "default": null,
      "items": {
        "type": "string",
        "enum": [
          "Bukkit",
          "Sponge",
          "Skript",
          "Minestom",
          "Datapack",
          "Fabric",
          "Forge",
          "Nukkit",
          "BehaviorPack",
          "PocketMine"
        ]
      },
      "minItems": 1
    },
    "status": {
      "type": ["string", "null"],
      "default": "Unknown",
      "enum": ["Active", "Inactive", "Discontinued", "Unknown", "Old", "Unavailable", null]
    },
    "versions": {
      "type": "string",
      "default": "Unknown",
      "minLength": 1
    },
    "spigot": {
      "type": ["integer", "null"],
      "default": null
    },
    "github": {
      "type": ["string", "null"],
      "default": null
    },
    "price": {
      "type": "string",
      "anyOf": [
        {},
        {
          "enum": ["Free"]
        }
      ]
    },
    "links": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": ["string", "null"],
            "anyOf": [
              {},
              {
                "enum": [
                  "GitHub",
                  "SpigotMC",
                  "Bukkit",
                  "BuiltByBit",
                  "Discord",
                  "Dedicated Site",
                  "BStats",
                  "Hangar",
                  "Polymart"
                ]
              }
            ]
          },
          "url": {
            "type": "string",
            "format": "uri",
            "pattern": "^https?://.*$"
          }
        },
        "required": ["name", "url"],
        "additionalProperties": false
      }
    }
  },
  "additionalProperties": false
}

=== ManInMyVan/Minecraft-Anticheat-List/src/jsMain/resources/anticheats/Argus.json
{
  "platforms": [
    "Bukkit"
  ],
  "status": "Old",
  "versions": "1.7.10",
  "spigot": null,
  "github": "Y4nN0xX/Argus-Anticheat-minecraft-1.7.10-Paladium",
  "price": "Free",
  "links": [
    {
      "name": "GitHub",
      "url": "https://github.com/Y4nN0xX/Argus-Anticheat-minecraft-1.7.10-Paladium"
    }
  ]
}

=== ManInMyVan/Minecraft-Anticheat-List/src/jsMain/resources/anticheats/GGIntegrity.json
{
  "platforms": [
    "Bukkit"
  ],
  "status": null,
  "versions": "1.20 - 1.21.7",
  "spigot": 124801,
  "github": null,
  "price": "Free",
  "links": [
    {
      "name": "SpigotMC",
      "url": "https://spigotmc.org/resources/124801"
    },
    {
      "name": "Discord",
      "url": "https://discord.gg/ZQx4wk2a3B"
    }
  ]
}

=== ManInMyVan/Minecraft-Anticheat-List/src/jsMain/resources/anticheats/Flappy.json
{
  "platforms": [
    "Bukkit"
  ],
  "status": null,
  "versions": "1.13 - 1.17",
  "spigot": 92180,
  "github": null,
  "price": "Free",
  "links": [
    {
      "name": "SpigotMC",
      "url": "https://spigotmc.org/resources/92180"
    },
    {
      "name": "Bukkit",
      "url": "https://dev.bukkit.org/projects/flappy-anticheat-1-16-1-17"
    }
  ]
}

=== ManInMyVan/Minecraft-Anticheat-List/src/jsMain/resources/anticheats/Matrix.json
{
  "platforms": [
    "Bukkit"
  ],
  "status": "Active",
  "versions": "1.8.8, 1.12.2 - 1.21",
  "spigot": null,
  "github": null,
  "price": "$22.00, $129.00, $15.00/mo $1300.00, $4000.00 (?)",
  "links": [
    {
      "name": "BuiltByBit",
      "url": "https://builtbybit.com/resources/13999"
    },
    {
      "name": "Dedicated Site",
      "url": "https://matrix.rip"
    },
    {
      "name": null,
      "url": "https://spigotmc.org/resources/64635"
    }
  ]
}

=== ManInMyVan/Minecraft-Anticheat-List/src/jsMain/resources/anticheats/Oxa AntiCheat.json
{
  "platforms": [
    "Bukkit"
  ],
  "status": "Discontinued",
  "versions": "1.12 - 1.20",
  "spigot": 113847,
  "github": null,
  "price": "Free",
  "links": [
    {
      "name": "SpigotMC",
      "url": "https://spigotmc.org/resources/113847"
    },
    {
      "name": "Discord",
      "url": "https://discord.gg/WqwVzEYcc9"
    }
  ]
}

=== ManInMyVan/Minecraft-Anticheat-List/src/jsMain/resources/anticheats/Bubble Anticheat Reborn.json
{
  "platforms": [
    "Skript"
  ],
  "status": null,
  "versions": "Unknown",
  "spigot": null,
  "github": "steviebeenz/BubbleAnticheatReborn",
  "price": "Free",
  "links": [
    {
      "name": "Dedicated Site",
      "url": "https://steviebeenz.github.io/BubbleAnticheatReborn"
    },
    {
      "name": "GitHub",
      "url": "https://github.com/steviebeenz/BubbleAnticheatReborn"
    }
  ]
}

=== ManInMyVan/Minecraft-Anticheat-List/src/jsMain/resources/anticheats/BetterAnticheat.json
{
  "platforms": [
    "Bukkit"
  ],
  "status": null,
  "versions": "1.21.4+",
  "spigot": null,
  "github": "amnoah/BetterAnticheat",
  "price": "Free",
  "links": [
    {
      "name": "GitHub",
      "url": "https://github.com/amnoah/BetterAnticheat"
    },
    {
      "name": "Modrinth",
      "url": "https://modrinth.com/plugin/betteranticheat"
    }
  ]
}

=== ManInMyVan/Minecraft-Anticheat-List/src/jsMain/resources/anticheats/NESS.json
{
  "platforms": [
    "Bukkit"
  ],
  "status": null,
  "versions": "1.8 - 1.12",
  "spigot": 53281,
  "github": "MSWS/NESS",
  "price": "Free",
  "links": [
    {
      "name": "SpigotMC",
      "url": "https://spigotmc.org/resources/53281"
    },
    {
      "name": "GitHub",
      "url": "https://github.com/MSWS/NESS"
    }
  ]
}
