=== ManInMyVan/Minecraft-Anticheat-List/src/jsMain/resources/schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Anticheat",
  "description": "Schema for anticheat entries.",
  "type": "object",
  "required": ["platforms", "status", "versions", "price"],
  "properties": {
    "platforms": {
      "type": ["array", "null"],
      "uniqueItems": true,
      "default": null,
      "items": {
        "type": "string",
        "enum": [
          "Bukkit",
          "Sponge",
          "Skript",
          "Minestom",
          "Datapack",
          "Fabric",
          "Forge",
          "Nukkit",
          "BehaviorPack",
          "PocketMine"
        ]
      },
      "minItems": 1
    },
    "status": {
      "type": ["string", "null"],
      "default": "Unknown",
      "enum": ["Active", "Inactive", "Discontinued", "Unknown", "Old", "Unavailable", null]
    },
    "versions": {
      "type": "string",
      "default": "Unknown",
      "minLength": 1
    },
    "spigot": {
      "type": ["integer", "null"],
      "default": null
    },
    "github": {
      "type": ["string", "null"],
      "default": null
    },
    "price": {
      "type": "string",
      "anyOf": [
        {},
        {
          "enum": ["Free"]
        }
      ]
    },
    "links": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": ["string", "null"],
            "anyOf": [
              {},
              {
                "enum": [
                  "GitHub",
                  "SpigotMC",
                  "Bukkit",
                  "BuiltByBit",
                  "Discord",
                  "Dedicated Site",
                  "BStats",
                  "Hangar",
                  "Polymart"
                ]
              }
            ]
          },
          "url": {
            "type": "string",
            "format": "uri",
            "pattern": "^https?://.*$"
          }
        },
        "required": ["name", "url"],
        "additionalProperties": false
      }
    }
  },
  "additionalProperties": false
}

=== ManInMyVan/Minecraft-Anticheat-List/src/jsMain/resources/anticheats/Grim.json
{
  "platforms": [
    "Bukkit"
  ],
  "status": null,
  "versions": "1.8.8, 1.12.2, 1.16 - 1.20.5",
  "spigot": 99923,
  "github": "GrimAnticheat/Grim",
  "price": "Free",
  "links": [
    {
      "name": "SpigotMC",
      "url": "https://spigotmc.org/resources/99923"
    },
    {
      "name": "GitHub",
      "url": "https://github.com/GrimAnticheat/Grim"
    },
    {
      "name": "Hanger",
      "url": "https://hangar.papermc.io/GrimAnticheat/GrimAnticheat"
    },
    {
      "name": "Dedicated Site",
      "url": "https://grim.ac"
    }
  ]
}

=== ManInMyVan/Minecraft-Anticheat-List/src/jsMain/resources/anticheats/AntiHaxerman.json
{
  "platforms": [
    "Bukkit"
  ],
  "status": null,
  "versions": "1.7 - 1.8",
  "spigot": 83198,
  "github": "Tecnio/AntiHaxerman",
  "price": "Free",
  "links": [
    {
      "name": "SpigotMC",
      "url": "https://spigotmc.org/resources/83198"
    },
    {
      "name": "GitHub",
      "url": "https://github.com/Tecnio/AntiHaxerman"
    }
  ]
}

=== ManInMyVan/Minecraft-Anticheat-List/src/jsMain/resources/anticheats/Daedalus.json
{
  "platforms": [
    "Bukkit"
  ],
  "status": "Discontinued",
  "versions": "1.7 - 1.13",
  "spigot": 49215,
  "github": "funkemunky/Daedalus",
  "price": "Free",
  "links": [
    {
      "name": "GitHub",
      "url": "https://github.com/funkemunky/Daedalus"
    },
    {
      "name": "SpigotMC",
      "url": "https://spigotmc.org/resources/49215"
    }
  ]
}

=== ManInMyVan/Minecraft-Anticheat-List/src/jsMain/resources/anticheats/Vulcan.json
{
  "platforms": [
    "Bukkit"
  ],
  "status": null,
  "versions": "1.8 - 26.2",
  "spigot": 83626,
  "github": null,
  "price": "$19.99 (USD)",
  "links": [
    {
      "name": "SpigotMC",
      "url": "https://spigotmc.org/resources/83626"
    },
    {
      "name": "Discord",
      "url": "https://discord.com/invite/SCNuwUG"
    }
  ]
}

=== ManInMyVan/Minecraft-Anticheat-List/src/jsMain/resources/anticheats/Hades.json
{
  "platforms": [
    "Bukkit"
  ],
  "status": "Inactive",
  "versions": "1.7 - 1.15",
  "spigot": 65622,
  "github": "Tecnio/Hades",
  "price": "Free",
  "links": [
    {
      "name": "GitHub",
      "url": "https://github.com/Tecnio/Hades"
    },
    {
      "name": "SpigotMC",
      "url": "https://spigotmc.org/resources/65622"
    }
  ]
}

=== ManInMyVan/Minecraft-Anticheat-List/src/jsMain/resources/anticheats/Astro.json
{
  "platforms": [
    "Bukkit"
  ],
  "status": "Active",
  "versions": "1.8+",
  "spigot": null,
  "github": null,
  "price": "$30.00 (?)",
  "links": [
    {
      "name": "Dedicated Site",
      "url": "https://astroac.gg"
    },
    {
      "name": "Discord",
      "url": "https://discord.gg/fJGspEJnyh"
    }
  ]
}

=== ManInMyVan/Minecraft-Anticheat-List/src/jsMain/resources/anticheats/ThotPatrol.json
{
  "platforms": [
    "Bukkit"
  ],
  "status": "Discontinued",
  "versions": "1.7 - 1.8",
  "spigot": 79978,
  "github": "freppp/ThotPatrol",
  "price": "Free",
  "links": [
    {
      "name": "SpigotMC",
      "url": "https://spigotmc.org/resources/79978"
    },
    {
      "name": "GitHub",
      "url": "https://github.com/freppp/ThotPatrol"
    }
  ]
}

=== ManInMyVan/Minecraft-Anticheat-List/src/jsMain/resources/anticheats/Spartan.json
{
  "platforms": [
    "Bukkit"
  ],
  "status": null,
  "versions": "1.7 - 1.21.5",
  "spigot": 123945,
  "github": null,
  "price": "Free, €19.99/y (EUR)",
  "links": [
    {
      "name": "SpigotMC",
      "url": "https://spigotmc.org/resources/123945"
    },
    {
      "name": "BuiltByBit",
      "url": "https://builtbybit.com/resources/bundle/1925"
    },
    {
      "name": "Hangar",
      "url": "https://hangar.papermc.io/IdealisticAI/Spartan-AntiCheat"
    }
  ]
}
